### ISSUE TITLE
Doesn't work with submodules

### ISSUE THREAD

**Issue by Gama11** [Cycloware/vscode-github-file-folder-url#1]
The "copy URL" command has the same issue as this similar extension when dealing with submodules:

https://github.com/d4rkr00t/vscode-open-in-github/issues/9

It simply creates a link to the file as if it were part of the root repository.

**Comment by KavanShaban** [comment]
This has been fixed in 1.1.0, full submodule support when enumerating configs and generating urls.

**Comment by Gama11** [comment]
Cool, I'll be sure to check it out once 1.1.0 is released.

**Comment by KavanShaban** [comment]
Great, 1.1 has been uploaded so please update.  Any reviews on the VsCode marketplace would be highly appreciated as well!

**Comment by Gama11** [comment]
Can confirm, works as expected now. 👍
