### ISSUE TITLE
Copy URL without markdown

### ISSUE THREAD

**Issue by Gama11** [Cycloware/vscode-github-file-folder-url#3]
More often than not, I'd like to copy URLs _without_ markdown-formatting. Could this be supported in some way? I guess there's at least three options for doing so:

- separate commands for copying without markdown
- a boolean setting
- open a picker after running a command that lets you select the desired formatting

The last option is probably the most flexible one, you could even add other formatting options in the future.

**Comment by KavanShaban** [comment]
So you are asking to copy just the url?  I can easily add separate commands and then you can just bind the key strokes you would like in your VSCode user settings.

This will go up today with the fix for #4.

**Comment by Gama11** [comment]
>So you are asking to copy just the url?

Yes, exactly.

My concern with adding separate commands was mostly that this would double the commands from 3 to 6.

**Comment by KavanShaban** [comment]
Added `*-simple` version of the commands to enable key binding for raw url copying.

**Comment by KavanShaban** [comment]
This has been added to version `1.2.0`

**Comment by Gama11** [comment]
Awesome, thanks!
