### ISSUE TITLE
"Copy GitHub URL for all open files" includes markdown previews

### ISSUE THREAD

**Issue by Gama11** [Cycloware/vscode-github-file-folder-url#4]
To reproduce, open a markdown file and then a markdown preview:

![](http://i.imgur.com/vgnTFdn.png)

Running "Copy GitHub URL for all open files" copies both "files", even though the preview of course isn't a real file / doesn't exist in the Git repo. It shows up with a `.md.rendered` extension.

Here's an example:

![](http://i.imgur.com/di0jpLW.png)

```markdown
[README.md](https://github.com/vshaxe/vshaxe/blob/master/README.md)
[README.md.rendered](https://github.com/vshaxe/vshaxe/blob/master/README.md.rendered)
```

**Comment by KavanShaban** [comment]
Thanks for pointing this out, I'll get a fix up today.

**Comment by KavanShaban** [comment]
Added a check to ensure file exists on disk and generate appropriate warnings/errors if not.

**Comment by KavanShaban** [comment]
This has been added to version `1.2.0`
